// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.roora.domain;

import java.lang.String;

privileged aspect Unit_Roo_JavaBean {
    
    public String Unit.getName() {
        return this.name;
    }
    
    public void Unit.setName(String name) {
        this.name = name;
    }
    
}
