// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.roora.domain;

import java.util.List;
import java.util.Random;
import org.roora.domain.MyOrder;
import org.roora.domain.PersonDataOnDemand;
import org.roora.domain.StoreDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MyOrderDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MyOrderDataOnDemand: @Component;
    
    private Random MyOrderDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<MyOrder> MyOrderDataOnDemand.data;
    
    @Autowired
    private StoreDataOnDemand MyOrderDataOnDemand.storeDataOnDemand;
    
    @Autowired
    private PersonDataOnDemand MyOrderDataOnDemand.personDataOnDemand;
    
    public MyOrder MyOrderDataOnDemand.getNewTransientMyOrder(int index) {
        org.roora.domain.MyOrder obj = new org.roora.domain.MyOrder();
        setCreated(obj, index);
        setDescription(obj, index);
        setStore(obj, index);
        setPerson(obj, index);
        return obj;
    }
    
    private void MyOrderDataOnDemand.setCreated(MyOrder obj, int index) {
        java.util.Date created = new java.util.GregorianCalendar(java.util.Calendar.getInstance().get(java.util.Calendar.YEAR), java.util.Calendar.getInstance().get(java.util.Calendar.MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY), java.util.Calendar.getInstance().get(java.util.Calendar.MINUTE), java.util.Calendar.getInstance().get(java.util.Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreated(created);
    }
    
    private void MyOrderDataOnDemand.setDescription(MyOrder obj, int index) {
        java.lang.String description = "description_" + index;
        obj.setDescription(description);
    }
    
    private void MyOrderDataOnDemand.setStore(MyOrder obj, int index) {
        org.roora.domain.Store store = storeDataOnDemand.getRandomStore();
        obj.setStore(store);
    }
    
    private void MyOrderDataOnDemand.setPerson(MyOrder obj, int index) {
        org.roora.domain.Person person = personDataOnDemand.getRandomPerson();
        obj.setPerson(person);
    }
    
    public MyOrder MyOrderDataOnDemand.getSpecificMyOrder(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        MyOrder obj = data.get(index);
        return MyOrder.findMyOrder(obj.getId());
    }
    
    public MyOrder MyOrderDataOnDemand.getRandomMyOrder() {
        init();
        MyOrder obj = data.get(rnd.nextInt(data.size()));
        return MyOrder.findMyOrder(obj.getId());
    }
    
    public boolean MyOrderDataOnDemand.modifyMyOrder(MyOrder obj) {
        return false;
    }
    
    public void MyOrderDataOnDemand.init() {
        data = org.roora.domain.MyOrder.findMyOrderEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'MyOrder' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.roora.domain.MyOrder>();
        for (int i = 0; i < 10; i++) {
            org.roora.domain.MyOrder obj = getNewTransientMyOrder(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
