// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.roora.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.roora.domain.MyOrderDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MyOrderIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MyOrderIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MyOrderIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: MyOrderIntegrationTest: @Transactional;
    
    @Autowired
    private MyOrderDataOnDemand MyOrderIntegrationTest.dod;
    
    @Test
    public void MyOrderIntegrationTest.testCountMyOrders() {
        org.junit.Assert.assertNotNull("Data on demand for 'MyOrder' failed to initialize correctly", dod.getRandomMyOrder());
        long count = org.roora.domain.MyOrder.countMyOrders();
        org.junit.Assert.assertTrue("Counter for 'MyOrder' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MyOrderIntegrationTest.testFindMyOrder() {
        org.roora.domain.MyOrder obj = dod.getRandomMyOrder();
        org.junit.Assert.assertNotNull("Data on demand for 'MyOrder' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MyOrder' failed to provide an identifier", id);
        obj = org.roora.domain.MyOrder.findMyOrder(id);
        org.junit.Assert.assertNotNull("Find method for 'MyOrder' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'MyOrder' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MyOrderIntegrationTest.testFindAllMyOrders() {
        org.junit.Assert.assertNotNull("Data on demand for 'MyOrder' failed to initialize correctly", dod.getRandomMyOrder());
        long count = org.roora.domain.MyOrder.countMyOrders();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'MyOrder', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.roora.domain.MyOrder> result = org.roora.domain.MyOrder.findAllMyOrders();
        org.junit.Assert.assertNotNull("Find all method for 'MyOrder' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'MyOrder' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MyOrderIntegrationTest.testFindMyOrderEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'MyOrder' failed to initialize correctly", dod.getRandomMyOrder());
        long count = org.roora.domain.MyOrder.countMyOrders();
        if (count > 20) count = 20;
        java.util.List<org.roora.domain.MyOrder> result = org.roora.domain.MyOrder.findMyOrderEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'MyOrder' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'MyOrder' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MyOrderIntegrationTest.testFlush() {
        org.roora.domain.MyOrder obj = dod.getRandomMyOrder();
        org.junit.Assert.assertNotNull("Data on demand for 'MyOrder' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MyOrder' failed to provide an identifier", id);
        obj = org.roora.domain.MyOrder.findMyOrder(id);
        org.junit.Assert.assertNotNull("Find method for 'MyOrder' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMyOrder(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'MyOrder' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MyOrderIntegrationTest.testMerge() {
        org.roora.domain.MyOrder obj = dod.getRandomMyOrder();
        org.junit.Assert.assertNotNull("Data on demand for 'MyOrder' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MyOrder' failed to provide an identifier", id);
        obj = org.roora.domain.MyOrder.findMyOrder(id);
        boolean modified =  dod.modifyMyOrder(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.roora.domain.MyOrder merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'MyOrder' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MyOrderIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'MyOrder' failed to initialize correctly", dod.getRandomMyOrder());
        org.roora.domain.MyOrder obj = dod.getNewTransientMyOrder(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'MyOrder' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'MyOrder' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'MyOrder' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MyOrderIntegrationTest.testRemove() {
        org.roora.domain.MyOrder obj = dod.getRandomMyOrder();
        org.junit.Assert.assertNotNull("Data on demand for 'MyOrder' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MyOrder' failed to provide an identifier", id);
        obj = org.roora.domain.MyOrder.findMyOrder(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'MyOrder' with identifier '" + id + "'", org.roora.domain.MyOrder.findMyOrder(id));
    }
    
}
