// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.roora.domain;

import java.lang.String;
import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.roora.domain.MyOrder;
import org.roora.domain.MyOrderDataOnDemand;
import org.roora.domain.OrderItem;
import org.roora.domain.Product;
import org.roora.domain.ProductDataOnDemand;
import org.roora.domain.Unit;
import org.roora.domain.UnitDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect OrderItemDataOnDemand_Roo_DataOnDemand {
    
    declare @type: OrderItemDataOnDemand: @Component;
    
    private Random OrderItemDataOnDemand.rnd = new SecureRandom();
    
    private List<OrderItem> OrderItemDataOnDemand.data;
    
    @Autowired
    private MyOrderDataOnDemand OrderItemDataOnDemand.myOrderDataOnDemand;
    
    @Autowired
    private ProductDataOnDemand OrderItemDataOnDemand.productDataOnDemand;
    
    @Autowired
    private UnitDataOnDemand OrderItemDataOnDemand.unitDataOnDemand;
    
    public OrderItem OrderItemDataOnDemand.getNewTransientOrderItem(int index) {
        OrderItem obj = new OrderItem();
        setDescription(obj, index);
        setMyOrder(obj, index);
        setProduct(obj, index);
        setQuantity(obj, index);
        setUnit(obj, index);
        return obj;
    }
    
    public void OrderItemDataOnDemand.setDescription(OrderItem obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void OrderItemDataOnDemand.setMyOrder(OrderItem obj, int index) {
        MyOrder myOrder = myOrderDataOnDemand.getRandomMyOrder();
        obj.setMyOrder(myOrder);
    }
    
    public void OrderItemDataOnDemand.setProduct(OrderItem obj, int index) {
        Product product = productDataOnDemand.getRandomProduct();
        obj.setProduct(product);
    }
    
    public void OrderItemDataOnDemand.setQuantity(OrderItem obj, int index) {
        BigDecimal quantity = BigDecimal.valueOf(index);
        obj.setQuantity(quantity);
    }
    
    public void OrderItemDataOnDemand.setUnit(OrderItem obj, int index) {
        Unit unit = unitDataOnDemand.getRandomUnit();
        obj.setUnit(unit);
    }
    
    public OrderItem OrderItemDataOnDemand.getSpecificOrderItem(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        OrderItem obj = data.get(index);
        return OrderItem.findOrderItem(obj.getId());
    }
    
    public OrderItem OrderItemDataOnDemand.getRandomOrderItem() {
        init();
        OrderItem obj = data.get(rnd.nextInt(data.size()));
        return OrderItem.findOrderItem(obj.getId());
    }
    
    public boolean OrderItemDataOnDemand.modifyOrderItem(OrderItem obj) {
        return false;
    }
    
    public void OrderItemDataOnDemand.init() {
        data = OrderItem.findOrderItemEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'OrderItem' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<org.roora.domain.OrderItem>();
        for (int i = 0; i < 10; i++) {
            OrderItem obj = getNewTransientOrderItem(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
