// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.roora.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.roora.domain.OrderItemDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect OrderItemIntegrationTest_Roo_IntegrationTest {
    
    declare @type: OrderItemIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: OrderItemIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: OrderItemIntegrationTest: @Transactional;
    
    @Autowired
    private OrderItemDataOnDemand OrderItemIntegrationTest.dod;
    
    @Test
    public void OrderItemIntegrationTest.testCountOrderItems() {
        org.junit.Assert.assertNotNull("Data on demand for 'OrderItem' failed to initialize correctly", dod.getRandomOrderItem());
        long count = org.roora.domain.OrderItem.countOrderItems();
        org.junit.Assert.assertTrue("Counter for 'OrderItem' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void OrderItemIntegrationTest.testFindOrderItem() {
        org.roora.domain.OrderItem obj = dod.getRandomOrderItem();
        org.junit.Assert.assertNotNull("Data on demand for 'OrderItem' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'OrderItem' failed to provide an identifier", id);
        obj = org.roora.domain.OrderItem.findOrderItem(id);
        org.junit.Assert.assertNotNull("Find method for 'OrderItem' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'OrderItem' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void OrderItemIntegrationTest.testFindAllOrderItems() {
        org.junit.Assert.assertNotNull("Data on demand for 'OrderItem' failed to initialize correctly", dod.getRandomOrderItem());
        long count = org.roora.domain.OrderItem.countOrderItems();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'OrderItem', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.roora.domain.OrderItem> result = org.roora.domain.OrderItem.findAllOrderItems();
        org.junit.Assert.assertNotNull("Find all method for 'OrderItem' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'OrderItem' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void OrderItemIntegrationTest.testFindOrderItemEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'OrderItem' failed to initialize correctly", dod.getRandomOrderItem());
        long count = org.roora.domain.OrderItem.countOrderItems();
        if (count > 20) count = 20;
        java.util.List<org.roora.domain.OrderItem> result = org.roora.domain.OrderItem.findOrderItemEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'OrderItem' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'OrderItem' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void OrderItemIntegrationTest.testFlush() {
        org.roora.domain.OrderItem obj = dod.getRandomOrderItem();
        org.junit.Assert.assertNotNull("Data on demand for 'OrderItem' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'OrderItem' failed to provide an identifier", id);
        obj = org.roora.domain.OrderItem.findOrderItem(id);
        org.junit.Assert.assertNotNull("Find method for 'OrderItem' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyOrderItem(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'OrderItem' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OrderItemIntegrationTest.testMerge() {
        org.roora.domain.OrderItem obj = dod.getRandomOrderItem();
        org.junit.Assert.assertNotNull("Data on demand for 'OrderItem' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'OrderItem' failed to provide an identifier", id);
        obj = org.roora.domain.OrderItem.findOrderItem(id);
        boolean modified =  dod.modifyOrderItem(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.roora.domain.OrderItem merged = (org.roora.domain.OrderItem) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'OrderItem' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OrderItemIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'OrderItem' failed to initialize correctly", dod.getRandomOrderItem());
        org.roora.domain.OrderItem obj = dod.getNewTransientOrderItem(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'OrderItem' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'OrderItem' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'OrderItem' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void OrderItemIntegrationTest.testRemove() {
        org.roora.domain.OrderItem obj = dod.getRandomOrderItem();
        org.junit.Assert.assertNotNull("Data on demand for 'OrderItem' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'OrderItem' failed to provide an identifier", id);
        obj = org.roora.domain.OrderItem.findOrderItem(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'OrderItem' with identifier '" + id + "'", org.roora.domain.OrderItem.findOrderItem(id));
    }
    
}
