// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.roora.domain;

import java.util.List;
import java.util.Random;
import org.roora.domain.PersonStatus;
import org.springframework.stereotype.Component;

privileged aspect PersonStatusDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PersonStatusDataOnDemand: @Component;
    
    private Random PersonStatusDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<PersonStatus> PersonStatusDataOnDemand.data;
    
    public PersonStatus PersonStatusDataOnDemand.getNewTransientPersonStatus(int index) {
        org.roora.domain.PersonStatus obj = new org.roora.domain.PersonStatus();
        setName(obj, index);
        return obj;
    }
    
    private void PersonStatusDataOnDemand.setName(PersonStatus obj, int index) {
        java.lang.String name = "name_" + index;
        obj.setName(name);
    }
    
    public PersonStatus PersonStatusDataOnDemand.getSpecificPersonStatus(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        PersonStatus obj = data.get(index);
        return PersonStatus.findPersonStatus(obj.getId());
    }
    
    public PersonStatus PersonStatusDataOnDemand.getRandomPersonStatus() {
        init();
        PersonStatus obj = data.get(rnd.nextInt(data.size()));
        return PersonStatus.findPersonStatus(obj.getId());
    }
    
    public boolean PersonStatusDataOnDemand.modifyPersonStatus(PersonStatus obj) {
        return false;
    }
    
    public void PersonStatusDataOnDemand.init() {
        data = org.roora.domain.PersonStatus.findPersonStatusEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'PersonStatus' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.roora.domain.PersonStatus>();
        for (int i = 0; i < 10; i++) {
            org.roora.domain.PersonStatus obj = getNewTransientPersonStatus(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
