// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.roora.domain;

import java.util.List;
import java.util.Random;
import org.roora.domain.Person;
import org.springframework.stereotype.Component;

privileged aspect PersonDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PersonDataOnDemand: @Component;
    
    private Random PersonDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Person> PersonDataOnDemand.data;
    
    public Person PersonDataOnDemand.getNewTransientPerson(int index) {
        org.roora.domain.Person obj = new org.roora.domain.Person();
        setEmail(obj, index);
        setFirstName(obj, index);
        setLastName(obj, index);
        setPassword(obj, index);
        return obj;
    }
    
    private void PersonDataOnDemand.setEmail(Person obj, int index) {
        java.lang.String email = "email_" + index;
        obj.setEmail(email);
    }
    
    private void PersonDataOnDemand.setFirstName(Person obj, int index) {
        java.lang.String firstName = "firstName_" + index;
        obj.setFirstName(firstName);
    }
    
    private void PersonDataOnDemand.setLastName(Person obj, int index) {
        java.lang.String lastName = "lastName_" + index;
        obj.setLastName(lastName);
    }
    
    private void PersonDataOnDemand.setPassword(Person obj, int index) {
        java.lang.String password = "password_" + index;
        obj.setPassword(password);
    }
    
    public Person PersonDataOnDemand.getSpecificPerson(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Person obj = data.get(index);
        return Person.findPerson(obj.getId());
    }
    
    public Person PersonDataOnDemand.getRandomPerson() {
        init();
        Person obj = data.get(rnd.nextInt(data.size()));
        return Person.findPerson(obj.getId());
    }
    
    public boolean PersonDataOnDemand.modifyPerson(Person obj) {
        return false;
    }
    
    public void PersonDataOnDemand.init() {
        data = org.roora.domain.Person.findPersonEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Person' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.roora.domain.Person>();
        for (int i = 0; i < 10; i++) {
            org.roora.domain.Person obj = getNewTransientPerson(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
