// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.roora.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.roora.domain.PersonStatusDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PersonStatusIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PersonStatusIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PersonStatusIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: PersonStatusIntegrationTest: @Transactional;
    
    @Autowired
    private PersonStatusDataOnDemand PersonStatusIntegrationTest.dod;
    
    @Test
    public void PersonStatusIntegrationTest.testCountPersonStatuses() {
        org.junit.Assert.assertNotNull("Data on demand for 'PersonStatus' failed to initialize correctly", dod.getRandomPersonStatus());
        long count = org.roora.domain.PersonStatus.countPersonStatuses();
        org.junit.Assert.assertTrue("Counter for 'PersonStatus' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PersonStatusIntegrationTest.testFindPersonStatus() {
        org.roora.domain.PersonStatus obj = dod.getRandomPersonStatus();
        org.junit.Assert.assertNotNull("Data on demand for 'PersonStatus' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PersonStatus' failed to provide an identifier", id);
        obj = org.roora.domain.PersonStatus.findPersonStatus(id);
        org.junit.Assert.assertNotNull("Find method for 'PersonStatus' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'PersonStatus' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PersonStatusIntegrationTest.testFindAllPersonStatuses() {
        org.junit.Assert.assertNotNull("Data on demand for 'PersonStatus' failed to initialize correctly", dod.getRandomPersonStatus());
        long count = org.roora.domain.PersonStatus.countPersonStatuses();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'PersonStatus', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.roora.domain.PersonStatus> result = org.roora.domain.PersonStatus.findAllPersonStatuses();
        org.junit.Assert.assertNotNull("Find all method for 'PersonStatus' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'PersonStatus' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PersonStatusIntegrationTest.testFindPersonStatusEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'PersonStatus' failed to initialize correctly", dod.getRandomPersonStatus());
        long count = org.roora.domain.PersonStatus.countPersonStatuses();
        if (count > 20) count = 20;
        java.util.List<org.roora.domain.PersonStatus> result = org.roora.domain.PersonStatus.findPersonStatusEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'PersonStatus' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'PersonStatus' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PersonStatusIntegrationTest.testFlush() {
        org.roora.domain.PersonStatus obj = dod.getRandomPersonStatus();
        org.junit.Assert.assertNotNull("Data on demand for 'PersonStatus' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PersonStatus' failed to provide an identifier", id);
        obj = org.roora.domain.PersonStatus.findPersonStatus(id);
        org.junit.Assert.assertNotNull("Find method for 'PersonStatus' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPersonStatus(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'PersonStatus' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PersonStatusIntegrationTest.testMerge() {
        org.roora.domain.PersonStatus obj = dod.getRandomPersonStatus();
        org.junit.Assert.assertNotNull("Data on demand for 'PersonStatus' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PersonStatus' failed to provide an identifier", id);
        obj = org.roora.domain.PersonStatus.findPersonStatus(id);
        boolean modified =  dod.modifyPersonStatus(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.roora.domain.PersonStatus merged = (org.roora.domain.PersonStatus) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'PersonStatus' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PersonStatusIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'PersonStatus' failed to initialize correctly", dod.getRandomPersonStatus());
        org.roora.domain.PersonStatus obj = dod.getNewTransientPersonStatus(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'PersonStatus' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'PersonStatus' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'PersonStatus' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PersonStatusIntegrationTest.testRemove() {
        org.roora.domain.PersonStatus obj = dod.getRandomPersonStatus();
        org.junit.Assert.assertNotNull("Data on demand for 'PersonStatus' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PersonStatus' failed to provide an identifier", id);
        obj = org.roora.domain.PersonStatus.findPersonStatus(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'PersonStatus' with identifier '" + id + "'", org.roora.domain.PersonStatus.findPersonStatus(id));
    }
    
}
