// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.roora.domain;

import java.util.List;
import java.util.Random;
import org.roora.domain.ProductStatus;
import org.springframework.stereotype.Component;

privileged aspect ProductStatusDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProductStatusDataOnDemand: @Component;
    
    private Random ProductStatusDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<ProductStatus> ProductStatusDataOnDemand.data;
    
    public ProductStatus ProductStatusDataOnDemand.getNewTransientProductStatus(int index) {
        org.roora.domain.ProductStatus obj = new org.roora.domain.ProductStatus();
        setName(obj, index);
        return obj;
    }
    
    private void ProductStatusDataOnDemand.setName(ProductStatus obj, int index) {
        java.lang.String name = "name_" + index;
        obj.setName(name);
    }
    
    public ProductStatus ProductStatusDataOnDemand.getSpecificProductStatus(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        ProductStatus obj = data.get(index);
        return ProductStatus.findProductStatus(obj.getId());
    }
    
    public ProductStatus ProductStatusDataOnDemand.getRandomProductStatus() {
        init();
        ProductStatus obj = data.get(rnd.nextInt(data.size()));
        return ProductStatus.findProductStatus(obj.getId());
    }
    
    public boolean ProductStatusDataOnDemand.modifyProductStatus(ProductStatus obj) {
        return false;
    }
    
    public void ProductStatusDataOnDemand.init() {
        data = org.roora.domain.ProductStatus.findProductStatusEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'ProductStatus' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.roora.domain.ProductStatus>();
        for (int i = 0; i < 10; i++) {
            org.roora.domain.ProductStatus obj = getNewTransientProductStatus(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
