// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.roora.domain;

import java.util.List;
import java.util.Random;
import org.roora.domain.ProductGroup;
import org.springframework.stereotype.Component;

privileged aspect ProductGroupDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProductGroupDataOnDemand: @Component;
    
    private Random ProductGroupDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<ProductGroup> ProductGroupDataOnDemand.data;
    
    public ProductGroup ProductGroupDataOnDemand.getNewTransientProductGroup(int index) {
        org.roora.domain.ProductGroup obj = new org.roora.domain.ProductGroup();
        setName(obj, index);
        setProductGroup(obj, index);
        return obj;
    }
    
    private void ProductGroupDataOnDemand.setName(ProductGroup obj, int index) {
        java.lang.String name = "name_" + index;
        obj.setName(name);
    }
    
    private void ProductGroupDataOnDemand.setProductGroup(ProductGroup obj, int index) {
        org.roora.domain.ProductGroup productGroup = obj;
        obj.setProductGroup(productGroup);
    }
    
    public ProductGroup ProductGroupDataOnDemand.getSpecificProductGroup(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        ProductGroup obj = data.get(index);
        return ProductGroup.findProductGroup(obj.getId());
    }
    
    public ProductGroup ProductGroupDataOnDemand.getRandomProductGroup() {
        init();
        ProductGroup obj = data.get(rnd.nextInt(data.size()));
        return ProductGroup.findProductGroup(obj.getId());
    }
    
    public boolean ProductGroupDataOnDemand.modifyProductGroup(ProductGroup obj) {
        return false;
    }
    
    public void ProductGroupDataOnDemand.init() {
        data = org.roora.domain.ProductGroup.findProductGroupEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'ProductGroup' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.roora.domain.ProductGroup>();
        for (int i = 0; i < 10; i++) {
            org.roora.domain.ProductGroup obj = getNewTransientProductGroup(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
