// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.roora.domain;

import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.roora.domain.ProductGroup;
import org.springframework.stereotype.Component;

privileged aspect ProductGroupDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProductGroupDataOnDemand: @Component;
    
    private Random ProductGroupDataOnDemand.rnd = new SecureRandom();
    
    private List<ProductGroup> ProductGroupDataOnDemand.data;
    
    public ProductGroup ProductGroupDataOnDemand.getNewTransientProductGroup(int index) {
        ProductGroup obj = new ProductGroup();
        setName(obj, index);
        setProductGroup(obj, index);
        return obj;
    }
    
    public void ProductGroupDataOnDemand.setName(ProductGroup obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void ProductGroupDataOnDemand.setProductGroup(ProductGroup obj, int index) {
        ProductGroup productGroup = obj;
        obj.setProductGroup(productGroup);
    }
    
    public ProductGroup ProductGroupDataOnDemand.getSpecificProductGroup(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        ProductGroup obj = data.get(index);
        return ProductGroup.findProductGroup(obj.getId());
    }
    
    public ProductGroup ProductGroupDataOnDemand.getRandomProductGroup() {
        init();
        ProductGroup obj = data.get(rnd.nextInt(data.size()));
        return ProductGroup.findProductGroup(obj.getId());
    }
    
    public boolean ProductGroupDataOnDemand.modifyProductGroup(ProductGroup obj) {
        return false;
    }
    
    public void ProductGroupDataOnDemand.init() {
        data = ProductGroup.findProductGroupEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'ProductGroup' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<org.roora.domain.ProductGroup>();
        for (int i = 0; i < 10; i++) {
            ProductGroup obj = getNewTransientProductGroup(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
