// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.roora.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.roora.domain.ProductStatusDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductStatusIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProductStatusIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProductStatusIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ProductStatusIntegrationTest: @Transactional;
    
    @Autowired
    private ProductStatusDataOnDemand ProductStatusIntegrationTest.dod;
    
    @Test
    public void ProductStatusIntegrationTest.testCountProductStatuses() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProductStatus' failed to initialize correctly", dod.getRandomProductStatus());
        long count = org.roora.domain.ProductStatus.countProductStatuses();
        org.junit.Assert.assertTrue("Counter for 'ProductStatus' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProductStatusIntegrationTest.testFindProductStatus() {
        org.roora.domain.ProductStatus obj = dod.getRandomProductStatus();
        org.junit.Assert.assertNotNull("Data on demand for 'ProductStatus' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProductStatus' failed to provide an identifier", id);
        obj = org.roora.domain.ProductStatus.findProductStatus(id);
        org.junit.Assert.assertNotNull("Find method for 'ProductStatus' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'ProductStatus' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProductStatusIntegrationTest.testFindAllProductStatuses() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProductStatus' failed to initialize correctly", dod.getRandomProductStatus());
        long count = org.roora.domain.ProductStatus.countProductStatuses();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'ProductStatus', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.roora.domain.ProductStatus> result = org.roora.domain.ProductStatus.findAllProductStatuses();
        org.junit.Assert.assertNotNull("Find all method for 'ProductStatus' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'ProductStatus' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProductStatusIntegrationTest.testFindProductStatusEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProductStatus' failed to initialize correctly", dod.getRandomProductStatus());
        long count = org.roora.domain.ProductStatus.countProductStatuses();
        if (count > 20) count = 20;
        java.util.List<org.roora.domain.ProductStatus> result = org.roora.domain.ProductStatus.findProductStatusEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'ProductStatus' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'ProductStatus' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProductStatusIntegrationTest.testFlush() {
        org.roora.domain.ProductStatus obj = dod.getRandomProductStatus();
        org.junit.Assert.assertNotNull("Data on demand for 'ProductStatus' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProductStatus' failed to provide an identifier", id);
        obj = org.roora.domain.ProductStatus.findProductStatus(id);
        org.junit.Assert.assertNotNull("Find method for 'ProductStatus' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProductStatus(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'ProductStatus' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductStatusIntegrationTest.testMerge() {
        org.roora.domain.ProductStatus obj = dod.getRandomProductStatus();
        org.junit.Assert.assertNotNull("Data on demand for 'ProductStatus' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProductStatus' failed to provide an identifier", id);
        obj = org.roora.domain.ProductStatus.findProductStatus(id);
        boolean modified =  dod.modifyProductStatus(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.roora.domain.ProductStatus merged = (org.roora.domain.ProductStatus) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'ProductStatus' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductStatusIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProductStatus' failed to initialize correctly", dod.getRandomProductStatus());
        org.roora.domain.ProductStatus obj = dod.getNewTransientProductStatus(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'ProductStatus' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'ProductStatus' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'ProductStatus' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProductStatusIntegrationTest.testRemove() {
        org.roora.domain.ProductStatus obj = dod.getRandomProductStatus();
        org.junit.Assert.assertNotNull("Data on demand for 'ProductStatus' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProductStatus' failed to provide an identifier", id);
        obj = org.roora.domain.ProductStatus.findProductStatus(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'ProductStatus' with identifier '" + id + "'", org.roora.domain.ProductStatus.findProductStatus(id));
    }
    
}
