// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.roora.domain;

import java.lang.Long;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.roora.domain.Sector;
import org.roora.domain.Store;
import org.roora.domain.StoreDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SectorDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SectorDataOnDemand: @Component;
    
    private Random SectorDataOnDemand.rnd = new SecureRandom();
    
    private List<Sector> SectorDataOnDemand.data;
    
    @Autowired
    private StoreDataOnDemand SectorDataOnDemand.storeDataOnDemand;
    
    public Sector SectorDataOnDemand.getNewTransientSector(int index) {
        Sector obj = new Sector();
        setName(obj, index);
        setOrderNum(obj, index);
        setStore(obj, index);
        return obj;
    }
    
    public void SectorDataOnDemand.setName(Sector obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void SectorDataOnDemand.setOrderNum(Sector obj, int index) {
        Long orderNum = new Integer(index).longValue();
        obj.setOrderNum(orderNum);
    }
    
    public void SectorDataOnDemand.setStore(Sector obj, int index) {
        Store store = storeDataOnDemand.getRandomStore();
        obj.setStore(store);
    }
    
    public Sector SectorDataOnDemand.getSpecificSector(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Sector obj = data.get(index);
        return Sector.findSector(obj.getId());
    }
    
    public Sector SectorDataOnDemand.getRandomSector() {
        init();
        Sector obj = data.get(rnd.nextInt(data.size()));
        return Sector.findSector(obj.getId());
    }
    
    public boolean SectorDataOnDemand.modifySector(Sector obj) {
        return false;
    }
    
    public void SectorDataOnDemand.init() {
        data = Sector.findSectorEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Sector' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<org.roora.domain.Sector>();
        for (int i = 0; i < 10; i++) {
            Sector obj = getNewTransientSector(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
