// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.roora.domain;

import java.util.List;
import java.util.Random;
import org.roora.domain.Sector;
import org.roora.domain.StoreDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SectorDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SectorDataOnDemand: @Component;
    
    private Random SectorDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Sector> SectorDataOnDemand.data;
    
    @Autowired
    private StoreDataOnDemand SectorDataOnDemand.storeDataOnDemand;
    
    public Sector SectorDataOnDemand.getNewTransientSector(int index) {
        org.roora.domain.Sector obj = new org.roora.domain.Sector();
        setName(obj, index);
        setOrderNum(obj, index);
        setStore(obj, index);
        return obj;
    }
    
    private void SectorDataOnDemand.setName(Sector obj, int index) {
        java.lang.String name = "name_" + index;
        obj.setName(name);
    }
    
    private void SectorDataOnDemand.setOrderNum(Sector obj, int index) {
        java.lang.Long orderNum = new Integer(index).longValue();
        obj.setOrderNum(orderNum);
    }
    
    private void SectorDataOnDemand.setStore(Sector obj, int index) {
        org.roora.domain.Store store = storeDataOnDemand.getRandomStore();
        obj.setStore(store);
    }
    
    public Sector SectorDataOnDemand.getSpecificSector(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Sector obj = data.get(index);
        return Sector.findSector(obj.getId());
    }
    
    public Sector SectorDataOnDemand.getRandomSector() {
        init();
        Sector obj = data.get(rnd.nextInt(data.size()));
        return Sector.findSector(obj.getId());
    }
    
    public boolean SectorDataOnDemand.modifySector(Sector obj) {
        return false;
    }
    
    public void SectorDataOnDemand.init() {
        data = org.roora.domain.Sector.findSectorEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Sector' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.roora.domain.Sector>();
        for (int i = 0; i < 10; i++) {
            org.roora.domain.Sector obj = getNewTransientSector(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
