// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.roora.domain;

import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.roora.domain.Store;
import org.springframework.stereotype.Component;

privileged aspect StoreDataOnDemand_Roo_DataOnDemand {
    
    declare @type: StoreDataOnDemand: @Component;
    
    private Random StoreDataOnDemand.rnd = new SecureRandom();
    
    private List<Store> StoreDataOnDemand.data;
    
    public Store StoreDataOnDemand.getNewTransientStore(int index) {
        Store obj = new Store();
        setName(obj, index);
        return obj;
    }
    
    public void StoreDataOnDemand.setName(Store obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public Store StoreDataOnDemand.getSpecificStore(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Store obj = data.get(index);
        return Store.findStore(obj.getId());
    }
    
    public Store StoreDataOnDemand.getRandomStore() {
        init();
        Store obj = data.get(rnd.nextInt(data.size()));
        return Store.findStore(obj.getId());
    }
    
    public boolean StoreDataOnDemand.modifyStore(Store obj) {
        return false;
    }
    
    public void StoreDataOnDemand.init() {
        data = Store.findStoreEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Store' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<org.roora.domain.Store>();
        for (int i = 0; i < 10; i++) {
            Store obj = getNewTransientStore(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
