// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.roora.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.roora.domain.StoreDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StoreIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StoreIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StoreIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: StoreIntegrationTest: @Transactional;
    
    @Autowired
    private StoreDataOnDemand StoreIntegrationTest.dod;
    
    @Test
    public void StoreIntegrationTest.testCountStores() {
        org.junit.Assert.assertNotNull("Data on demand for 'Store' failed to initialize correctly", dod.getRandomStore());
        long count = org.roora.domain.Store.countStores();
        org.junit.Assert.assertTrue("Counter for 'Store' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StoreIntegrationTest.testFindStore() {
        org.roora.domain.Store obj = dod.getRandomStore();
        org.junit.Assert.assertNotNull("Data on demand for 'Store' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Store' failed to provide an identifier", id);
        obj = org.roora.domain.Store.findStore(id);
        org.junit.Assert.assertNotNull("Find method for 'Store' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Store' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StoreIntegrationTest.testFindAllStores() {
        org.junit.Assert.assertNotNull("Data on demand for 'Store' failed to initialize correctly", dod.getRandomStore());
        long count = org.roora.domain.Store.countStores();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Store', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.roora.domain.Store> result = org.roora.domain.Store.findAllStores();
        org.junit.Assert.assertNotNull("Find all method for 'Store' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Store' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StoreIntegrationTest.testFindStoreEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Store' failed to initialize correctly", dod.getRandomStore());
        long count = org.roora.domain.Store.countStores();
        if (count > 20) count = 20;
        java.util.List<org.roora.domain.Store> result = org.roora.domain.Store.findStoreEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Store' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Store' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StoreIntegrationTest.testFlush() {
        org.roora.domain.Store obj = dod.getRandomStore();
        org.junit.Assert.assertNotNull("Data on demand for 'Store' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Store' failed to provide an identifier", id);
        obj = org.roora.domain.Store.findStore(id);
        org.junit.Assert.assertNotNull("Find method for 'Store' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyStore(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Store' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StoreIntegrationTest.testMerge() {
        org.roora.domain.Store obj = dod.getRandomStore();
        org.junit.Assert.assertNotNull("Data on demand for 'Store' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Store' failed to provide an identifier", id);
        obj = org.roora.domain.Store.findStore(id);
        boolean modified =  dod.modifyStore(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.roora.domain.Store merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Store' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StoreIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Store' failed to initialize correctly", dod.getRandomStore());
        org.roora.domain.Store obj = dod.getNewTransientStore(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Store' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Store' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Store' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StoreIntegrationTest.testRemove() {
        org.roora.domain.Store obj = dod.getRandomStore();
        org.junit.Assert.assertNotNull("Data on demand for 'Store' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Store' failed to provide an identifier", id);
        obj = org.roora.domain.Store.findStore(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Store' with identifier '" + id + "'", org.roora.domain.Store.findStore(id));
    }
    
}
