// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.roora.domain;

import java.util.List;
import java.util.Random;
import org.roora.domain.Store;
import org.springframework.stereotype.Component;

privileged aspect StoreDataOnDemand_Roo_DataOnDemand {
    
    declare @type: StoreDataOnDemand: @Component;
    
    private Random StoreDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Store> StoreDataOnDemand.data;
    
    public Store StoreDataOnDemand.getNewTransientStore(int index) {
        org.roora.domain.Store obj = new org.roora.domain.Store();
        setName(obj, index);
        return obj;
    }
    
    private void StoreDataOnDemand.setName(Store obj, int index) {
        java.lang.String name = "name_" + index;
        obj.setName(name);
    }
    
    public Store StoreDataOnDemand.getSpecificStore(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Store obj = data.get(index);
        return Store.findStore(obj.getId());
    }
    
    public Store StoreDataOnDemand.getRandomStore() {
        init();
        Store obj = data.get(rnd.nextInt(data.size()));
        return Store.findStore(obj.getId());
    }
    
    public boolean StoreDataOnDemand.modifyStore(Store obj) {
        return false;
    }
    
    public void StoreDataOnDemand.init() {
        data = org.roora.domain.Store.findStoreEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Store' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.roora.domain.Store>();
        for (int i = 0; i < 10; i++) {
            org.roora.domain.Store obj = getNewTransientStore(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
