// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.roora.domain;

import org.roora.domain.UnitIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UnitIntegrationTest_Roo_Configurable {
    
    declare @type: UnitIntegrationTest: @Configurable;
    
}
